// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0TxRV5jQTcBEFj0Z7zGttV7lE1V6GxE',
    appId: '1:238571059644:web:bd7098f00fe5909f94d3b9',
    messagingSenderId: '238571059644',
    projectId: 'newsapp-d7466',
    authDomain: 'newsapp-d7466.firebaseapp.com',
    storageBucket: 'newsapp-d7466.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUBnvHNWGHXsvP32BL2VcgtT8jS3i49bM',
    appId: '1:238571059644:android:700b74b6304d2af594d3b9',
    messagingSenderId: '238571059644',
    projectId: 'newsapp-d7466',
    storageBucket: 'newsapp-d7466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Sp557ncF21ZiNkIIzTNxPvikmau1ISM',
    appId: '1:238571059644:ios:bda62585b9c940b494d3b9',
    messagingSenderId: '238571059644',
    projectId: 'newsapp-d7466',
    storageBucket: 'newsapp-d7466.appspot.com',
    iosBundleId: 'com.example.flutterApplicationNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Sp557ncF21ZiNkIIzTNxPvikmau1ISM',
    appId: '1:238571059644:ios:98052c741837205194d3b9',
    messagingSenderId: '238571059644',
    projectId: 'newsapp-d7466',
    storageBucket: 'newsapp-d7466.appspot.com',
    iosBundleId: 'com.example.flutterApplicationNews.RunnerTests',
  );
}
